baseurl = "https://giodi.dev/"
title = "Giodi website"
theme = "PaperMod"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Giodi - Diletta Calà Impirotta website"
    description = "Blog italiano sull'industria del software"
    github = "https://github.com/giodi-ci"
    twitter = "https://twitter.com/GioDi_CI"
    email = "giodidev@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5