baseurl = "https://diletta.dev/"
title = "Diletta"
theme = "candor-hugo-theme"
defaultContentLanguage = "it"

[Params]
    mainSections = ["post"]
    intro = true
    title = "Diletta"
    author = "Diletta Calà Impirotta"
    headline = "Diletta Calà Impirotta personal website"
    description = "Personal website and italian Blog about software engineering management"
    keywords = ["Curriculum", "Blog", "Software Engineering Manager"]
    github = "https://github.com/diletta-ci"
    twitter = "https://twitter.com/DilettaCi"
    email = "g.calaimpirotta@gmail.com"
    opengraph = true
    shareTwitter = true
    DateFormat = "January 2, 2006"
    defaultTheme = "light"
    disableThemeToggle = true
    
    ShowToc = true
    TocOpen = false
    UseHugoToc = true

    ShowReadingTime = true
    ShowWordCount = false
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = false
    ShowCodeCopyButtons = false

    ShowRssButtonInSectionTermList = false
    disableSpecial1stPost = false
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = false

[Permalinks]
    post = "/:filename/"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5